[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sihutils"
version = "0.1.0"
description = "Utility helpers for SIH workflows"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.9"
# (in addition to default jupyterlab dependencies)
dependencies = [
    "pynvml",
    "pandas",
    "etils",
    "protobuf",
    "absl-py",
    "comfy-cli",
]

[project.urls]
Homepage = "https://github.com/TheSingularityIsHere/sihutils"
Repository = "https://github.com/TheSingularityIsHere/sihutils"

[tool.setuptools.packages.find]
where = ["."]
include = ["sihutils*"]

[tool.setuptools.package-data]
sihutils = ["*.json"]
